### ISSUE TITLE
How to make a better guess about Brick Class by changing abbreviation mapping

### ISSUE THREAD

**Issue by lfh19961021** [BrickSchema/reconciliation-api#2]
Hello,
When I try to convert the CSV to brick model, I found that there have different accuracy if I split the column into a different number of column, for example:

Some metadata split into 1 column can make a better guess
![image](https://user-images.githubusercontent.com/57752031/108150990-b0873b00-7110-11eb-9e17-fe3beb8b03f0.png)
Some metadata split into 2 columns can make a better guess
![image](https://user-images.githubusercontent.com/57752031/108150963-a2391f00-7110-11eb-97c1-cbc8b4809165.png)

I am thinking it may be the abbreviation mapping does not contain the data about "AUTO" in image 2, so I am trying to expand the abbreviation mapping in abbrmap.py.
If I want to add some data on it to make a better guess about Brick Class by changing abbreviation mapping
What should I do and anythings or rules I need to pay attention to?

**Comment by Advitya17** [comment]
I'll be working on it and opening a PR for the same in a week. Stay tuned! :)

Additionally, you can also try out our tool, [AutoBrick](https://github.com/Advitya17/AutoBrickify), which utilizes the Recon. API, automates and accelerates the entire Brickification process end-to-end, and literally returns the output brick turtle file in seconds!

**Comment by Advitya17** [comment]
Here're the PR - https://github.com/BrickSchema/reconciliation-api/pull/3

Let me know if you need additional mappings to be added to the same. Hope this helps.

**Comment by gtfierro** [comment]
Hi @lfh19961021. Essentially, the abbrmap needs to point an abbreviation (e.g. `AUTO`) to some Brick tags, which are defined in the `Brick.ttl` file. It will choose as a guess the class which has the highest degree of overlap of tags between it and the input abbreviations. See [this documentation](https://docs.brickschema.org/metadata/tags.html) for how to figure out what tags are defined in Brick and which map to which classes. You can also inspect the Brick.ttl file directly

One of the things we are considering adding is adding other columns from the OpenRefine representation as input to the Reconciliation server, so that it can leverage additional context if it needs to.

@Advitya17 I would be very interested to learn how AutoBrick chooses the best splitting for the labels! That is potentially a very compelling feature
